name: Auto Fill Course Info

on:
  workflow_dispatch:      # 允许手动触发
  schedule:
    - cron: '0 20 * * *'  # 每天北京时间凌晨4点 (UTC 20:00) 跑一次整理

jobs:
  fill-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests selenium webdriver-manager

      - name: Run Script
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
          # 这里只需要作业库的 ID
          FEISHU_LIB_TABLE_ID: ${{ secrets.FEISHU_LIB_TABLE_ID }}
          SCHOOLOGY_COOKIES: ${{ secrets.SCHOOLOGY_COOKIES }}
        run: python fill_course_info.py
